### ISSUE TITLE
Filter check command to show only outdated

### ISSUE THREAD

**Issue by ComLock** [versioneye/veye#22]
```sh
veye check Gemfile.lock --outdated
```
Instead of

```sh
$ veye check Gemfile.lock | grep outdated
```

To show only outdated gems.

**Comment by reiz** [comment]
Good idea :-) /cc @timgluz

**Comment by timgluz** [comment]
Hi, 

i'm not sure about this functionality - i want to keep this tool as simple as possible and there're very good cmd-line tools for filtering - csv & grep, json & jq etc; 

yes, it makes some sense filtering results in table and pretty view; specially when dealing with big projects;

I need to think it through.

**Comment by reiz** [comment]
@timgluz I think it makes sense. I want to see the bad stuff. That's the most interesting part because that is my homework to fix it as a developer. We have the same feature in the Web Interface. If you click on a project you come to a [summary report](http://blog.versioneye.com/2015/06/10/project-summary-report/) which only shows the out-dated and unknown dependencies. The "green" dependencies are hidden by default. /cc @ComLock

**Comment by reiz** [comment]
This is related to #38 . I think showing only the out-dated dependencies should be the default for `veye check`. I want to see my homework :-)

**Comment by timgluz** [comment]
done, check also #38 .
