### ISSUE TITLE
Make it possible to set name, privacy when uploading project and store it in .veye.yml

### ISSUE THREAD

**Issue by ComLock** [versioneye/veye#25]
Something like:
```sh
be veye projects upload Gemfile.lock --name='My project' --private > .veye.yml
````

Then the other projects commands should read project_key from .veye.yml

**Comment by ComLock** [comment]
Perhaps also collaborators, or another command to add/remove them

**Comment by reiz** [comment]
That's a good idea.

**Comment by timgluz** [comment]
@reiz Can i tweak project parameters via API? It will be helpful when i can pass some query-parameters for visibility when uploading project.

And managing collaborators is great idea and i'll open new issue for that.

**Comment by timgluz** [comment]
I like the idea adding aliases for projects to make managing projects simpler and names will be more memorizable too. 

i'm currently thinking that it should also recognize current project by working directory

**Comment by timgluz** [comment]
@reiz Maybe it makes more sense to use API to manage project names? a user and collaborators can see same name via cmd-line tool and on the website;

**Comment by reiz** [comment]
@timgluz I just added the more optional parameters to the upload endpoint. Now you can set this params in the HTTP POST request
 
 - visibility : Either 'private' or 'public'
 - name : The desired name of the new VersionEye project. 

![screen shot 2015-07-09 at 11 59 07](https://cloud.githubusercontent.com/assets/652130/8593647/db3848da-2639-11e5-8303-2e31ecb72f43.png)

Somehow it doesn't work in SwaggerUI. Somehow SwaggerUI is not sending the values of the 2 new fields to the server. But I wrote a test case for the these new params that's why I know that it's working.

**Comment by reiz** [comment]
@ComLock @timgluz The `project.name` is the label which gets displayed in the [projects overview](https://www.versioneye.com/user/projects) and in the project detail view. It is **not** unique. If a project file gets uploaded via the API, VersionEye tries to figure out the name of the project. Some project files like package.json, composer.json, pom.xml support a `name` attribute. If that is not empty we take that as the name of the project. If it is empty we take the fileanme as name of the project. Now with the new API the name of the project can be set explicitly at creation time. Beside that the project can be renamed easily in the project detail view. 

![screen shot 2015-07-09 at 13 09 28](https://cloud.githubusercontent.com/assets/652130/8593874/f06982c6-263b-11e5-9b0c-d1288c592bdd.png)

**Comment by timgluz** [comment]
Done;
