### ISSUE TITLE
Only show out-dated dependencies for veye check

### ISSUE THREAD

**Issue by reiz** [versioneye/veye#38]
I just executed 

```
veye check Gemfile.lock
```

My `Gemfile.lock` has more than 100 Gems. The tool out putted a long list with all my Gems and I had scroll up to see which of them is out-dated. 

![screen shot 2015-09-02 at 10 29 57](https://cloud.githubusercontent.com/assets/652130/9626488/3d4ff316-515e-11e5-8e94-a0472ce26ca0.png)

Indeed I'm not interested in all the "green" dependencies. I'm only interested in the "red" dependencies. Just show me my homework. Would be nice to print out only the X dependencies which are out-dated. If all dependencies are up-to-date then I would expect a simple message like `Thumbs up dude. Your dependencies are all up-to-date. Keep up the good work.` ;-)

**Comment by timgluz** [comment]
ok, sounds reasonable.

check also: #22  Filter check command to show only outdated

**Comment by timgluz** [comment]
Now it shows only outdated packages by default. It's still possible to see all the dependencies using  `--all` flag, then it will show outdated packages first and green ones later.

It doesnt show the KoolAid-Dude message, because it's CLI tool and showing this message makes piping results to other cmd-line tools more difficult.

**Comment by reiz** [comment]
:+1:
